### PR TITLE
Custom image size - lets the user decide which size to generate

### PR DESCRIPTION
**Pull request by danielalcalde**
Let the user decide which image size to generate

### CODE REVIEW

**Comment by thndrbrrr** [comment]
@danielalcalde Hi Daniel – this PR contains your earlier Windows fix, which has been merged already. (Thanks again!) It's easier to see what's going on if the PRs are on their own feature branches.

**Review by thndrbrrr — CHANGES_REQUESTED** [review]
I see an issue here where, when you're working with a larger file than the default 512x512, and you forget to update height and width then suddenly you get a smaller image.

I'm thinking it would be better to have the default values for width and height as `-1`, meaning that the values should be determined automatically based on the image size (current behavior). Otherwise the given params will override.

This would become even more important for inpainting when you're working on truly large files, but just make a rectangular selection of the area you want to send over for inpainting.

**Comment by danielalcalde** [comment]
That sounds like a good idea, I think the best would be to have the default for image to image and inpainting to be a string "same". And if this string is not set then it defaults to the current behavior.

**Comment by thndrbrrr** [comment]
Have a look at the branch [wip/rect-select-inpainting](https://github.com/tgiesselmann/gimp-stable-boy/tree/wip/rect-select-inpainting).

It allows you to select which part you want to generate, and that determines the height and width values. Otherwise the image's size is used.

**Comment by thndrbrrr** [comment]
Closing this since processing size is now handled dynamically based on image size, rectangular selection, or inpainting region.

**Pull request closed without merging**
